spring:
  ai:
    openai:
      api-key: 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
